config/routes.rb
Intersection::Application.routes.draw do
  resources :stories

  resources :events

  resources :surveys
  resources :survey_responses
  match "/my_surveys", :controller => :survey_responses, :action => :index
  resources :teams

  resources :links

  resources :projects do 
    resources :links
  end

  resources :profiles

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users
  
  match "/projects/:project_name", :controller => :projects, :action => :show
  match "/teams/:team_name", :controller => :teams, :action => :show
  match "/profiles/:name", :controller => :profiles, :action => :show

  root :to => "home#index"

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :links, :dependent => :destroy
  has_many :project_milestones, :dependent => :destroy
  has_many :milestones, :through => :project_milestones, :uniq => true
  has_many :team_projects, :dependent => :destroy
  has_many :teams, :through => :team_projects
  has_many :project_users, :dependent => :destroy
  has_many :users, :through => :project_users, :uniq => true
  has_many :activities
  has_many :survey_responses, :as => :surveyable
  has_many :stories
  
  accepts_nested_attributes_for :links, :allow_destroy => true
  accepts_nested_attributes_for :project_milestones, :allow_destroy => true
  accepts_nested_attributes_for :project_users, :allow_destroy => true
  accepts_nested_attributes_for :team_projects, :allow_destroy => true
  
  scope :active, where(:active => true)
  scope :featured, where(:featured => true)
  
  validates_presence_of :name

  after_create 'create_activity("started")'
  after_update 'create_activity("updated")'

  acts_as_taggable

  def self.grouped
    group("date(projects.created_at)").size
  end

  def self.month_group
    projects=self.grouped.map { |x| {"#{x[0].to_date.strftime("%m/%y")}" =>  x[1]} }
    projects.inject{|memo, el| memo.merge( el ){|k, old_v, new_v| old_v + new_v}}
  end

  def active_milestone
    am = project_milestones.where(:active => true)
    if am.blank?
      am
    else
      am.first
    end
  end

  def to_url
    "<a href='/projects/#{self.name}'>#{self.name}</a>"
  end

  def survey_average(time1=1.month.ago, time2=Time.now)
  resp_array = self.survey_responses.taken.during(time1, time2)
  if resp_array.size > 0
    resp_array.collect(&:response).sum/resp_array.size
  else
    0
  end
  end

  def create_activity(activity)
    if $current_user
      if $current_user.profile
        Activity.create(:user => $current_user, :project => self, :activity =>
            "#{$current_user.profile.to_url} ")
      else
        Activity.create(:project => self, :user => $current_user, :activity => "#{self.to_url} #{activity}.")
      end
    else
    Activity.create(:project => self, :activity =>
      "#{self.to_url} #{activity}.")
    end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < InheritedResources::Base
  before_filter :authenticate_user!, :except => [:index, :show]

  def index
    @search = Project.tagged_with(["quick win"],:exclude => true).search(params[:search])

    if params[:search].nil?
      @search =  Project.tagged_with(["quick win"],:exclude => true).search
    elsif  params[:search][:taggings_tag_name_contains] == "quick win"
      @search = Project.search(params[:search])
    else
      @search = Project.tagged_with(["quick win"],:exclude => true).search(params[:search])
    end

    @projects = @search.order("created_at DESC")
  end

  def show
    @project = params[:id].to_i==0 ? Project.where(:name => params[:id]).first : Project.find(params[:id])
  end


end

app/helpers/projects_helper.rb
module ProjectsHelper

  def on_schedule(milestone_history)
    if milestone_history.completed_date.blank?
      if milestone_history.planned_date.present?
        schedule = milestone_history.planned_date.to_time - Time.now        
        if schedule < -1209600
          "red_schedule"
        elsif schedule < 0
          "yellow_schedule"
        elsif schedule > 0
          "green_schedule"
        end
      end
    end
  end

end

app/views/projects/_charts.html.erb
<% milestone_status_data = @projects.map { |x| x.active_milestone.milestone}.group_by(&:id).map{|k,v| [k, v.length]}.sort!%>
<% milestone_chart_data = milestone_status_data.map { |x| ["#{Milestone.find(x[0]).name}", x[1]] }%>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
  google.load('visualization', '1.0', {'packages':['corechart']});
  google.setOnLoadCallback(drawChart);

  function drawChart() {
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Milestone');
    data.addColumn('number', 'projects');
    data.addRows(<%=raw(milestone_chart_data)%>);
    var options = {'title':'Project Milestone Status','width':600,'height':300};
    var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));
    chart.draw(data, options);
    var pie_chart = new google.visualization.PieChart(document.getElementById('pie_chart'));
    pie_chart.draw(data, options);
  }
</script>
<div class="row">
<div id="chart_div" class="span6"></div>
<div id="pie_chart" class="span6"></div>
</div>

app/views/projects/_form.html.haml
= nested_form_for @project do |f|
  -if @project.errors.any?
    #error_explanation
      %h2= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg
  .clearfix
    = f.label :name
    .input
      = f.text_field :name
  .clearfix
    = f.label :description
    .input
      = f.text_area :description
  .clearfix
    = f.label :impact_statement
    .input
      = f.text_area :impact_statement
  .clearfix
    = f.label :tag_list
    .input
      = f.text_field :tag_list
  .clearfix
    = f.label :active
    .input
      = f.check_box :active
  - if !@project.new_record?
    %h2 Project Links
    =f.link_to_add "Add Link",:links
    %p
    =f.fields_for :links do |link|
      = link.text_field :name
      = link.text_field :url
      = link.select(:link_type_id, LinkType.all.collect {|p| [ p.name, p.id ] }, {:include_blank => false})
      = link.link_to_remove "Remove"
    %h2
      Project Milestones
    =f.link_to_add "Add Milestone",:project_milestones
    %p
    %table
      %thead
        %tr
          %td="Milestone"
          %td="Planned date"
          %td="Completed On"
          %td="Active"
          %td    
      %tbody
        =f.fields_for :project_milestones do |pm|
          %tr
            %td=pm.select(:milestone_id, Milestone.all.collect { |p| [p.name, p.id]}, {:include_blank => false})

            %td=pm.text_field :planned_date, :class => "datepicker", :value => (pm.object.planned_date.strftime("%Y-%m-%d") unless pm.object.planned_date.nil?)
            %td=pm.text_field :completed_date, :class => "datepicker", :value => (pm.object.completed_date.strftime("%Y-%m-%d") unless pm.object.completed_date.nil?)
            %td= pm.check_box("active")
            %td= pm.link_to_remove "Remove"
    %h2
      Project Members
    = f.link_to_add "Add Member",:project_users
    %p  
    =f.fields_for :project_users do |u|
      = u.select(:user_id, User.all.collect { |p| [p.profile.try(:name), p.id]}, {:include_blank => false})
      = u.link_to_remove "Remove"
    %h2
      Cities
    = f.link_to_add "Add City",:team_projects
    %p  
    =f.fields_for :team_projects do |u|
      = u.select(:team_id, Team.all.collect { |p| [p.name, p.id]}, {:include_blank => false})
      = u.link_to_remove "Remove"
  .actions
    = f.submit 'Save',{:class => "btn primary"}

app/views/projects/_project.html.haml
%tr
  %td
    %h3= link_to project.name, project
  %td= project.tag_list
  %td
    %ul
      -project.teams.each do |team|
        %li
          =link_to team.name, team_path(team)
  -if current_user
    %td
      =raw(r_y_g(project.survey_average)) if project.active?
  %td= project.active? ? raw('<span class="label label-success">Yes</span>') : raw('<span class="label label-important">No</span>')
  %td
    -active_milestones = project.project_milestones.where(:active => true)
    -if active_milestones.present?
      =active_milestones.first.milestone.name
  %td
    %div.bar_graph
      -if active_milestones.present?
        %div{:class => "size_#{active_milestones.first.milestone_id} #{on_schedule(active_milestones.first)}"}
  %td
    -if project.project_milestones.present?
      =project.updated_at.strftime("%m-%d-%Y")
  -if current_user
    %td
      = link_to 'Edit', edit_project_path(project)
      |
      =link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete

app/views/projects/_project_summary.html.haml
-network = team.network_growth
%h2 City Stats
%ul
  %li
    %strong 
      =link_to team.projects.size, "/teams/#{team.name}"
    Projects
  %li
    %strong 
      =team.all_members.size
    Team Members
  

app/views/projects/_search_form.html.haml
%tr
  %td
    = f.text_field :name_contains,:class=>"search_medium"
  %td
    =f.text_field :taggings_tag_name_contains,:class=>"search_medium"
  %td
    = f.text_field :teams_name_contains, :class => "search_medium"
  %td
  %td
    = f.check_box :active_equals, :checked => true
  %td
    = f.select "project_milestones_milestone_id_equals", Milestone.all.collect { |m| [m.name, m.id]}, {:include_blank => true}
  %td
  %td
  %td
    =f.submit "Submit", :value=>"Search", :class=>"btn info"
    =link_to "Clear", projects_path

app/views/projects/edit.html.haml
.div{:class=>"row"}
  .span16
    %h1 Editing project
  .span4
    = link_to 'Show', @project
    \|
    = link_to 'Back', projects_path
  .span16
    =render 'form'

app/views/projects/index.html.haml
%h1.floated
  ="Projects (#{@projects.size})"
#new
  = link_to 'New Project', new_project_path, :class=> "btn btn-primary" if current_user
=form_for @search do |f|
  %table.table.table-striped
    %tr
      %th Name
      %th Tags
      %th Team
      -if current_user
        %th Survey
      %th Active
      %th Milestone
      %th Progress
      %th Last Updated
      %th

    %tbody  
      =render @projects

%br

app/views/projects/new.html.haml
%h1 New project
= render 'form'

= link_to 'Back', projects_path

app/views/projects/show.html.haml
%p#notice= notice
.row
  .span12
    %h2=@project.name
    = link_to 'Edit', edit_project_path(@project) if current_user
.row
  .span6.stats
    -if current_user
      %h2 Survey Trends
      =render :partial => "surveys/survey_trend", :locals => {:trends => @project.survey_responses.trends_by_response}
    .clearfix
    %h2 Cities
    %ul
      %li
        -@project.teams.each do |team|
          -if team==@project.teams.last
            =raw(team.to_url)
          -else
            =raw(team.to_url) + ", "
    %h2 Team Members
    %ul.team_members
      -@project.users.each do |user|
        %li
          =link_to gravatar_image_tag(user.email, :alt => user.profile.try(:name)), user.profile
          %br
          =link_to user.profile.try(:name), user.profile
    .clearfix
    %h2 Links
    %ul
      -@project.links.each do |link|
        %li
          =link_to link.name, link.name
          ="(#{link.link_type.name})"
  .span6.stats
    %h2 Details
    %ul
      %li
        %b Description:
        =@project.description
      %li
        %b Impact:
        =@project.impact_statement
      %li
        %b Tags:
        =@project.tag_list
    %h2 Milestones
    -active_milestones = @project.project_milestones.where(:active => true)
    %ul
      %li
        %div.bar_graph
          -if active_milestones.present?
            %div{:class => "size_#{active_milestones.first.milestone_id} #{on_schedule(active_milestones.first)}"}
      -@project.project_milestones.each do |milestone|
        %li.milestone{:class => "#{milestone.active? ? 'active' : 'inactive'}"}
          %span.name
            =milestone.milestone.name
          %br
          -if milestone.completed_date?
            %span.completed
              Completed On
              =milestone.completed_date.strftime("%m-%d-%y")
          -else
            %span.planned
              Planned Completion On:
              - unless milestone.planned_date.nil?
                = milestone.planned_date.strftime("%m-%d-%y")


.tabbable
  %ul.nav.nav-tabs
    %li.active
      %a{:href=>"#1", 'data-toggle' => 'tab'} Comment Stream
    %li
      %a{:href=>"#2", 'data-toggle' => 'tab'} Stories
    %li
      %a{:href=>"#3", 'data-toggle' => 'tab'} Activity
    %li
      %a{:href=>"#4", 'data-toggle' => 'tab'} Pivotal Tracker Activity
    %li
      %a{:href=>"#5", 'data-toggle' => 'tab'} Github Activity
    - if current_user and current_user.admin?
      %li
        %a{:href=>"#6", 'data-toggle' => 'tab'} Surveys
  .tab-content
    .tab-pane.active#1
      %ul
      - @project.survey_responses.taken.order("updated_at DESC").each do |comment|
        %li=comment.note unless comment.note.nil?
    .tab-pane#2
      %ul
        -@project.stories.each do |story|
          %li
            =story.team.name + ": " if story.team
            =story.project.name + ": " if story.project
            story.story
    .tab-pane#3
      %ul
        -@project.activities.order("updated_at DESC").each do |activity|
          %li
            =raw(activity.activity)
    .tab-pane#4
      Coming soon!
    .tab-pane#5
      Coming soon!
    - if current_user and current_user.admin?
      .tab-pane{:id => "surveys"}
        %table
          %tr
            %th Date
            %th Survey
            %th Value
            %th Name
            %th Comments
            - @project.survey_responses.order("updated_at DESC").each do |sr|
              %tr
                %td=sr.updated_at.strftime("%m/%d/%y")
                %td=survey_name(sr)
                %td=raw(r_y_g(sr.response))
                %td=link_to sr.user.profile.try(:name), sr.user.profile
                %td=sr.note