config/routes.rb
Intersection::Application.routes.draw do
  resources :stories

  resources :events

  resources :surveys
  resources :survey_responses
  match "/my_surveys", :controller => :survey_responses, :action => :index
  resources :teams

  resources :links

  resources :projects do 
    resources :links
  end

  resources :profiles

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users
  
  match "/projects/:project_name", :controller => :projects, :action => :show
  match "/teams/:team_name", :controller => :teams, :action => :show
  match "/profiles/:name", :controller => :profiles, :action => :show

  root :to => "home#index"

end

app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :user
  belongs_to :team
  belongs_to :project
  default_scope order("updated_at DESC")


end

app/controllers/stories_controller.rb
class StoriesController < InheritedResources::Base
  before_filter :authenticate_user!, :except => [:show, :index]
  respond_to :html, :js
  
  def index
    @search = Story.search(params[:search])
    @stories = @search
  end
  
  def create
    @story = current_user.stories.new(params[:story])
    
      if @story.save
        flash[:notice] = 'Story Saved'
        respond_with @story, :location => stories_url
      else
        respond_with @story
      end
  end

end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.haml
= form_for @story do |f|
  -if @story.errors.any?
    #error_explanation
      %h2= "#{pluralize(@story.errors.count, "error")} prohibited this story from being saved:"
      %ul
        - @story.errors.full_messages.each do |msg|
          %li= msg
  .clearfix
    = f.label :project_id
    .input
      = f.select(:project_id, Project.all.map {|x| [x.name, x.id]}, :include_blank => true)
  .clearfix
    = f.label :team_id
    .input
      = f.select(:team_id, Team.all.map {|x| [x.name, x.id]}, :include_blank => true)
  .clearfix
    = f.label :story
    .input
      = f.text_area :story
  .actions
    = f.submit 'Save'

app/views/stories/create.js.erb
$("form#new_story").hide();
$("form#new_story").find('textarea,input[type="text"],select').val("");
$("form#new_story").find('input[type="submit"]').val("Save");
$("form#new_story").find('div.validation-error').empty();
$(".flashes").append("<div class='alert-message success fade in' data-alert='alert'><a class= 'close' href='#'>x</a><p><strong><%=notice%></strong></p></div>");
<% flash[:notice] = nil %>

app/views/stories/edit.html.haml
%h1 Editing story

= render 'form'

= link_to 'Show', @story
\|
= link_to 'Back', stories_path

app/views/stories/index.html.haml
%h1.floated Code for America 2012 Stories
#new
  = link_to 'New Story', new_story_path, :class => "btn btn-primary"  if current_user
%table.table
  %tr
    %th Submitted by
    %th Project
    %th Team
    %th Story
    %th

  - @stories.each do |story|
    %tr
      %td
        -if story.user
          = link_to story.user.name, story.user.profile
      %td
        -if story.project
          = link_to story.project.name, story.project if story.project
      %td
        -if story.team
          = link_to story.team.name, story.team if story.team
      %td
        = story.story
      %td
        = link_to 'Show', story
        -if current_user
          = link_to 'Edit', edit_story_path(story)
          = link_to 'Destroy', story, :confirm => 'Are you sure?', :method => :delete

app/views/stories/new.html.haml
%h1 New story

= render 'form'

= link_to 'Back', stories_path

app/views/stories/show.html.haml
%p#notice= notice

%p
  %b User:
  = @story.user_id
%p
  %b Project:
  = @story.project_id
%p
  %b Team:
  = @story.team_id
%p
  %b Story:
  = @story.story

= link_to 'Edit', edit_story_path(@story)
\|
= link_to 'Back', stories_path