config/routes.rb
Intersection::Application.routes.draw do
  resources :stories

  resources :events

  resources :surveys
  resources :survey_responses
  match "/my_surveys", :controller => :survey_responses, :action => :index
  resources :teams

  resources :links

  resources :projects do 
    resources :links
  end

  resources :profiles

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users
  
  match "/projects/:project_name", :controller => :projects, :action => :show
  match "/teams/:team_name", :controller => :teams, :action => :show
  match "/profiles/:name", :controller => :profiles, :action => :show

  root :to => "home#index"

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  validates_presence_of :survey_type, :name, :scale, :start_date, :end_date, :frequency
  has_many :survey_responses, :dependent => :destroy
  after_save :check_and_add_responses
  scope :active_surveys, where("surveys.end_date > ?", Time.now)

  def survey_today?
    schedule = IceCube::Schedule.new(self.start_date, {:end_time => self.end_date})
    schedule.add_recurrence_rule IceCube::Rule.weekly(self.frequency.to_i).day(self.start_date.wday)
    schedule.occurs_on?(Time.now)
  end

  def check_and_add_responses
   generate_survey_responses if self.survey_today?
  end

  def delete_expired_responses
    self.survey_responses.expired.not_taken.delete_all
  end

  def generate_survey_responses
    case self.survey_type
    when "Fellow"
      generate_fellow_survey_responses
    when "Team"
      generate_team_survey_responses
    when "Project"
      generate_project_survey_responses
    when "Staff"
      generate_staff_survey_responses
    when "City"
      generate_city_survey_responses
    end

  end

  def generate_fellow_survey_responses
    Profile.where(:user_type => "Fellow").each do |p|
      self.survey_responses.create(:user => p.user, :code =>"#{p.user.id}fellow#{Time.now.strftime('%d%m%y')}" ,:expires_on => Time.now + (self.frequency.to_i).weeks, :surveyable_type => "User", :surveyable_id => p.user.id)
    end
  end

  def generate_city_survey_responses
    Profile.where(:user_type => "City").each do |p|
      self.survey_responses.create(:user => p.user, :code =>"#{p.user.id}city#{Time.now.strftime('%d%m%y')}" ,:expires_on => Time.now + (self.frequency.to_i).weeks, :surveyable_type => "User", :surveyable_id => p.user.id)
    end
  end

  def generate_staff_survey_responses
    Profile.where(:user_type => "Staff").each do |p|
      self.survey_responses.create(:user => p.user, :code =>"#{p.user.id}staff#{Time.now.strftime('%d%m%y')}" ,:expires_on => Time.now + (self.frequency.to_i).weeks, :surveyable_type => "User", :surveyable_id => p.user.id)
    end
  end

  def generate_team_survey_responses
    Team.active_teams.each do |team|
      team.users.each do |u|
        self.survey_responses.create(:user => u, :code =>"#{u.id}team#{team.id}#{Time.now.strftime('%d%m%y')}" , :expires_on => Time.now + (self.frequency.to_i).weeks, :surveyable_type => "Team", :surveyable_id => team.id)
      end
    end
  end

  def generate_project_survey_responses
    Project.active.each do |project|
      project.users.each do |u|
        self.survey_responses.create(:user => u, :code =>"#{u.id}project#{project.id}#{Time.now.strftime('%d%m%y')}" , :expires_on => Time.now + (self.frequency.to_i).weeks, :surveyable_type => "Project", :surveyable_id => project.id)
      end
    end
  end

end

app/controllers/surveys_controller.rb
class SurveysController < InheritedResources::Base
  before_filter :authenticate_user!
  before_filter :is_admin?
  
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.haml
= form_for @survey do |f|
  -if @survey.errors.any?
    #error_explanation
      %h2= "#{pluralize(@survey.errors.count, "error")} prohibited this survey from being saved:"
      %ul
        - @survey.errors.full_messages.each do |msg|
          %li= msg

  .clearfix
    = f.label "Survey Question:"
    .input
      = f.text_field :name
      %span.help-block
        This will appear on the survey response page
  .clearfix
    = f.label :survey_type
    .input
      = select(:survey, :survey_type, ["Fellow","Team","Project","Client","Staff"])
      %span.help-block
        Who or What is this survey about. I.e. Choose 'Fellow' if its about a fellow 
  .clearfix
    = f.label :scale
    .input
      = f.text_field :scale, :value => 3
      %span.help-block
        Enter an integer like 6 for a scale of 0 to 6.
  .clearfix
    = f.label :start_date
    .input
      = f.text_field :start_date, :class => "datepicker"
  .clearfix
    = f.label :end_date
    .input
      = f.text_field :end_date, :class => "datepicker"
  .clearfix
    = f.label :frequency
    .input
      = select(:survey, :frequency, [["1.weeks",1], ["2.weeks",2], ["3.weeks",3],["4.weeks",4],["5.weeks",5],["6.weeks",6],["7.weeks",7],["8.weeks",8]])
      %span.help-block
        The survey will get deployed every X numbers of weeks from the start date
  .actions
    = f.submit 'Save'

app/views/surveys/_survey_trend.html.haml
%ul.trends
  -trends[0..12].each do |trend|
    %li.show_date
      -i=3
      =trend[0].to_date.strftime("%m-%d")
      %ul{:id => "survey"}
        -trend[1].reverse.each do |t|
          %li
            =raw(trend_r_y_g(i,t))
            -i-=1

app/views/surveys/edit.html.haml
%h1 Editing survey

= render 'form'

= link_to 'Show', @survey
\|
= link_to 'Back', surveys_path

app/views/surveys/index.html.haml
%h1 Surveys

%table
  %tr
    %th Name
    %th Survey type
    %th Start date
    %th End date
    %th Frequency
    %th

  - @surveys.each do |survey|
    %tr
      %td
        =link_to survey.name, survey
        %br
        =render :partial => "survey_trend", :locals => {:trends => survey.survey_responses.trends_by_response}
      %td= survey.survey_type
      %td= survey.start_date.strftime("%m/%d/%y")
      %td= survey.end_date.strftime("%m/%d/%y")
      %td
        ="#{survey.frequency} weeks"
      %td
        = link_to 'Edit', edit_survey_path(survey)
        = link_to 'Destroy', survey, :confirm => 'Are you sure?', :method => :delete
%br

= link_to 'New Survey', new_survey_path

app/views/surveys/new.html.haml
%h1 New survey

= render 'form'

= link_to 'Back', surveys_path

app/views/surveys/show.html.haml
%p#notice= notice

.row
  .span16
    %h2= @survey.name
    ="Administered between #{@survey.start_date.strftime('%m-%d-%y')} and #{@survey.end_date.strftime('%m-%d-%y')} every #{@survey.frequency} weeks"
.row
  .span16       
    %h3 Trends
    =render :partial => "surveys/survey_trend", :locals => {:trends => @survey.survey_responses.trends_by_response}
%p
.rowi
  .span16
    -if current_user and current_user.admin?
      %h3 Survey Responses
      %table
        %tr
          %th Date
          %th About
          %th Value
          %th Submitted By
          %th Comments
        -@survey.survey_responses.order("updated_at DESC").each do |sr|
          %tr
            %td=sr.created_at.strftime("%m/%d/%y")
            -if sr.surveyable_type== "User"
              %td=link_to sr.surveyable.name, "/profiles/#{sr.surveyable.profile.id}"
            -else
              %td=link_to sr.surveyable.name, sr.surveyable
            %td=raw(r_y_g(sr.response))
            %td=link_to sr.user.profile.try(:name), sr.user.profile
            %td=sr.note