config/routes.rb
Intersection::Application.routes.draw do
  resources :stories

  resources :events

  resources :surveys
  resources :survey_responses
  match "/my_surveys", :controller => :survey_responses, :action => :index
  resources :teams

  resources :links

  resources :projects do 
    resources :links
  end

  resources :profiles

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users
  
  match "/projects/:project_name", :controller => :projects, :action => :show
  match "/teams/:team_name", :controller => :teams, :action => :show
  match "/profiles/:name", :controller => :profiles, :action => :show

  root :to => "home#index"

end

app/views/layouts/application.html.haml
<!DOCTYPE html>

%html{:lang => "en"}
  %head
    %title Intersection
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %script{:type => "text/javascript"}
      var _gaq=_gaq||[];_gaq.push(["_setAccount","UA-20825280-7"]),_gaq.push(["_setDomainName",".adoptahydrant.org"]),_gaq.push(["_trackPageview"]),function(){var a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src=("https:"==document.location.protocol?"https://ssl":"http://www")+".google-analytics.com/ga.js";var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)}();  
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    / Le styles
    %link{:href => "/css/bootstrap.css", :rel => "stylesheet"}/
    :css
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
        %link{:href => "/css/bootstrap-responsive.css", :rel => "stylesheet"}/
    / Le fav and touch icons
    %link{:href => "images/favicon.ico", :rel => "shortcut icon"}/
    %link{:href => "images/apple-touch-icon.png", :rel => "apple-touch-icon"}/
    %link{:href => "images/apple-touch-icon-72x72.png", :rel => "apple-touch-icon", :sizes => "72x72"}/
    %link{:href => "images/apple-touch-icon-114x114.png", :rel => "apple-touch-icon", :sizes => "114x114"}/
  %body{ :style => 'padding-top: 80px;', "data-controller" => controller_name, "data-action" => action_name, :class => controller_name }
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          .nav-collapse
            %ul.nav
              %li
                = image_tag('CfA_logo.png', :class => 'logo')
              %li
                = link_to 'Intersection', root_path, :class => 'brand'
              %li
                = link_to 'Cities', teams_path, :class => "cities"
                %ul.submenu.clearfix
                  -Team.order("name").each do |team|
                    %li
                      =link_to team.name, "/teams/#{team.name}"
              %li
                = link_to 'Projects', projects_path
              %li
                = link_to 'Fellows', profiles_path
              %li
                = link_to 'Events', events_path
              %li
                = link_to 'Stories', stories_path
            %ul.nav.pull-right
              -if current_user
                %li
                  = link_to "My Surveys", "/my_surveys"
                -if current_user.try(:admin?)
                  %li
                    = link_to 'Surveys', surveys_path
                -if current_user.admin?
                  %li
                    =link_to "Admin", rails_admin_path
                %li
                  = link_to('Logout', destroy_user_session_path, :method => :delete)
                %li
                  .gravatar
                    = link_to(gravatar_image_tag(current_user.email, :alt => current_user.profile.name), profile_path(current_user.profile))
              -if !user_signed_in?
                %li
                  = link_to('Login', new_user_session_path)
          / /.nav-collapse
    .container
      .row
        .span12.flashes
          - if flash[:notice]
            .div{:class => 'alert fade in'}
              %a.close{'data-dissmiss' => 'alert', :href=> '#'} x
              %strong
                = notice
          - if flash[:alert]
            .div{:class => 'alert fade in'}
              %a.close{'data-dissmiss' => 'alert', :href=> '#'} x
              %strong
                = alert


      = yield